### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by Eflores89** [gvegayon/PDSR#1]
Hi, i'm not sure if the data source changed or something, but I get an error while attempting the example in the readme:

``` r
library(PDSR)
apollo <- dirMissions("apollo 17")
```

Gives: 

``` r
Conecting to http://pds.jpl.nasa.gov/tools/dsstatus/
Error : failed to load external entity "http://pds.jpl.nasa.gov/tools/dsstatus/dsidStatus.jsp?sortOpt1=di.dsid&sortOpt2=&sortOpt3=&sortOpt4=&sortOpt5=&nodename=ALL&col2=dm.msnname&col3=&col4=&col5=&Go=Submit"

Error en dirMissions("apollo 17") : Connection failed.
```

**Comment by gvegayon** [comment]
Hi Eduardo -

Unfortunately I haven't work on this package for more than a year and I don't think I'll be working on it any time soon. Still, you are welcome to submit patches via fork!

Thanks anyway!

**Comment by gvegayon** [comment]
I thought you never were going to close this issue!
